// Lightweight metadata only. Project bodies are loaded on demand by DiscoverDetail.
const projects = [
  { slug: 'flashattention', date: '2026-08-28 21:00', name: 'FlashAttention', description: 'FlashAttention 不改变标准 attention 的输出，而是重新安排 Q、K、V 和中间结果在 GPU memory hierarchy 中的流动。本文从三个 score 的数值例子开始，依次解释 dense 与 sparse attention、HBM 与 SRAM、tiling、online softmax、backward recomputation，以及它在训练、prefill 和 decode 中的不同作用。最后区分 KV cache 与 PagedAttention，并梳理 FA1 到 FA4 的演进。', tags: ['Inference'], url: 'https://github.com/Dao-AILab/flash-attention', url2: 'https://arxiv.org/abs/2205.14135', stars: '24.8k', author: 'Shannon' },
  { slug: 'verl', date: '2026-08-28 20:00', name: 'verl', description: 'verl 是面向大语言模型强化学习后训练的分布式训练框架。本文从两个 prompt、每题四条 rollout 的一轮 GRPO 开始，逐项追踪 actor、rollout、reference policy、critic 与 reward 的输入输出，再说明 HybridFlow 如何把算法控制流、分布式模型计算和 GPU 放置分开。最后讨论 FSDP、Megatron、vLLM、SGLang、权重同步、共置部署以及排查训练吞吐的方法。', tags: ['Post-training'], url: 'https://github.com/verl-project/verl', url2: 'https://arxiv.org/abs/2409.19256', stars: '22.7k', author: 'Shannon' },
  { slug: 'vllm', date: '2026-08-28 18:00', name: 'vLLM', description: 'vLLM 是面向高并发大模型服务的推理引擎。本文从三个同时到达的请求出发，区分 prefill 与 decode，计算 KV cache 的显存占用，再说明 continuous batching、PagedAttention、chunked prefill、prefix caching 与 speculative decoding 如何共同影响吞吐和延迟。最后给出并行部署、基准测试与同类工具的适用边界。', tags: ['Inference'], url: 'https://github.com/vllm-project/vllm', url2: 'https://arxiv.org/abs/2309.06180', stars: '90.2k', author: 'Shannon' },
  { slug: 'llama-cpp', date: '2026-08-18 16:31', name: 'llama.cpp', description: 'llama.cpp 是一个 C/C++ 本地推理库,可以把 7B 模型量化到约 4.5GB,并在笔记本、树莓派和手机等设备上运行。本文说明量化、GGUF、KV cache、内存带宽限制、CPU/GPU 分工以及同类工具的适用场景。', tags: ['Inference'], url: 'https://github.com/ggml-org/llama.cpp', url2: 'https://github.com/ggml-org/ggml', stars: '124k+', author: 'Shannon' },
  { slug: 'mineru', date: '2026-08-17 16:20', name: 'MinerU', description: 'MinerU 通过八道工序把 PDF 转换为 Markdown,OCR 只是其中一道。本文先区分数字生成的 PDF 和扫描件,再说明版面检测、公式识别、表格重建与阅读顺序。OCR 由检测和识别两步组成,引擎采用 PaddleOCR 的 PyTorch 移植版。最后比较 Marker、Docling、PaddleOCR、PyMuPDF、Nougat、Zerox 与云服务的适用场景。', tags: ['RAG'], url: 'https://github.com/opendatalab/MinerU', url2: 'https://github.com/opendatalab/PDF-Extract-Kit', stars: '77.8k', author: 'Shannon' },
  { slug: 'superpowers-openspec', date: '2026-08-14 16:30', name: 'Superpowers + OpenSpec', description: 'Superpowers 为 AI 编程代理提供结构化工程流程,OpenSpec 提供 spec 驱动的行为契约。本文按契约、隔离、拆解、验证和上线五个阶段,说明两者在存量系统中的分工与边界。', tags: ['Agent'], url: 'https://github.com/obra/superpowers', url2: 'https://github.com/Fission-AI/OpenSpec', stars: '237k+ / 56k+', author: 'Obra (Prime Radiant) / Fission AI' },
  { slug: 'langgraph', date: '2026-07-31 20:30', name: 'LangGraph', description: '用图定义 Agent 行为的框架。节点就是函数，边就是逻辑，编译后是确定性的执行拓扑——不是"建议"Agent 怎么走，是它只能这么走。', tags: ['Agent'], url: 'https://github.com/langchain-ai/langgraph', stars: '60k+', author: 'LangChain' },
  { slug: 'multica', date: '2026-07-30 11:30', name: 'Multica', description: '一个开源的多智能体管理平台,用于向 AI 编程代理分配 Issue,并记录代理的代码修改、阻塞状态和执行进度。', tags: ['Agent'], url: 'https://github.com/multica-ai/multica', stars: '42k+', author: 'multica-ai' },
  { slug: 'pi', date: '2026-07-29 10:08', name: 'Pi Agent Harness', description: '一个保持较小核心功能集的 AI Agent 工具包，提供统一的多供应商 LLM 接口、带差分渲染的 TUI、可扩展的 Agent 运行时和编码 Agent CLI。', tags: ['Agent'], url: 'https://github.com/earendil-works/pi', stars: '79.5k+', author: 'earendil-works' },
  { slug: 'openai-agents-python', date: '2026-07-29 00:21', name: 'OpenAI Agents SDK', description: 'OpenAI 官方发布的 Python SDK，用于构建多智能体工作流。支持 100+ 大语言模型，提供 Agent 编排、沙箱、护栏、追踪等基础设施。', tags: ['Agent'], url: 'https://github.com/openai/openai-agents-python', stars: '28k+', author: 'OpenAI' },
  { slug: 'symphony', date: '2026-07-27 20:42', name: 'Symphony', description: 'OpenAI 的自主编码自动化参考实现。监控 Linear 面板，自动派发 AI 代理实现任务，要求提供工作量证明后才能合入代码。', tags: ['Agent'], url: 'https://github.com/openai/symphony', stars: '26k+', author: 'OpenAI' },
  { slug: 'okf', date: '2026-07-27 16:24', name: 'Open Knowledge Format (OKF)', description: '开放知识格式，用 Markdown 文件加 YAML 前置元数据来表示知识。设计为人可读、AI 代理也可消费。', tags: ['RAG'], url: 'https://github.com/GoogleCloudPlatform/knowledge-catalog', stars: '7.8k+', author: 'Google Cloud' },
].sort((a, b) => b.date.localeCompare(a.date))

export default projects
